### ISSUE TITLE
Error while installing deepspeech 

### ISSUE THREAD

**Issue by Yuumna** [calebchiam/asr-react#3]
Got error while installing the requirements.txt are there any updated version for the project with deepspeech v 0.9.3
ERROR: Could not find a version that satisfies the requirement deepspeech==0.5.1 
ERROR: No matching distribution found for deepspeech==0.5.1

**Comment by calebchiam** [comment]
Hi @Yuumna, sorry I'm not actively maintaining this project. You could just change it to v0.9.3 in requirements.txt and see if it works!
